---
- name: pip install glance
  command: pip install -i {{ openstack.pypi_mirror }} /opt/stack/glance
  register: result
  until: result|success
  retries: 3
  delay: 60

- name: restart glance services
  restart_if_present: service={{ item }}
  with_items:
    - glance-api
    - glance-registry

- name: restart btsync
  action: service name=btsync state=restarted enabled=yes
