---
- name: Check if cinder user exists
  action: shell getent passwd cinder
  register: cinder_user
  ignore_errors: True
  changed_when: False

- name: cinder user
  user: name=cinder shell=/bin/false createhome=no
  when: cinder_user.rc == 0

- name: cinder user
  user: name=cinder comment=cinder shell=/bin/false system=yes home=/nonexistent createhome=no
  when: cinder_user.rc != 0

- name: get cinder source repo
  git: |
    repo={{ openstack.git_mirror }}/cinder.git 
    dest=/opt/stack/cinder 
    version={{ cinder.rev }}
    update={{ openstack.git_update }}
  notify:
    - pip install cinder
    - cinder rootwrap
- meta: flush_handlers

- name: /etc/cinder
  file: dest=/etc/cinder state=directory

- file: dest=/var/lib/cinder state=directory owner=cinder group=cinder
- file: dest=/var/lib/cinder/images state=directory owner=cinder group=cinder
- file: dest=/var/cache/cinder state=directory mode=0700 owner=cinder group=cinder

- name: cinder config
  action: template src={{ item }} dest=/etc/cinder mode=0644
  with_fileglob: ../templates/etc/cinder/*
  notify: restart cinder services

- name: cinder sudoer
  template: src=etc/sudoers.d/cinder dest=/etc/sudoers.d/cinder owner=root group=root mode=0440
