---
- name: Check if glance user exists
  action: shell getent passwd glance
  register: glance_user
  ignore_errors: True
  changed_when: False

- name: glance user
  user: name=glance shell=/bin/false createhome=no
  when: glance_user.rc == 0

- name: glance user
  user: name=glance comment=glance shell=/bin/false system=yes home=/nonexistent createhome=no
  when: glance_user.rc != 0

- name: get glance source repo
  git: |
    repo={{ openstack.git_mirror }}/glance.git 
    dest=/opt/stack/glance 
    version={{ glance.rev }} 
    update={{ openstack.git_update }}
  notify:
    - pip install glance
    - restart glance services
- meta: flush_handlers

- name: /etc/glance
  file: dest=/etc/glance state=directory

- file: dest=/var/lib/glance state=directory owner=glance group=glance
- file: dest=/var/lib/glance/images state=directory owner=glance group=glance
- file: dest=/var/cache/glance state=directory mode=0700 owner=glance group=glance

- name: glance config
  action: template src={{ item }} dest=/etc/glance mode=0644
  with_fileglob: ../templates/etc/glance/*
  notify:
    - restart glance services

- name: setup glance image replication
  include: image-sync.yml
  when: glance.sync.enabled
