---
- sensu_process_check: service={{ item }}
  with_items:
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
  notify: restart sensu-client

- sensu_process_check: service=neutron-lbaas-agent
  notify: restart sensu-client
  when: neutron.enable_lbaas

- sensu_process_check: service=/usr/local/sbin/ipchanged
