---
- apt: pkg=ufw

- name: permit ucarp (IP protocol 112)
  lineinfile: dest=/etc/ufw/before.rules regexp="^-A ufw-before-input -p 112 -j ACCEPT" line="-A ufw-before-input -p 112 -j ACCEPT" insertafter="^-A ufw-before-input -p udp --sport 67 --dport 68 -j ACCEPT"

- name: Permit SSH
  command: ufw allow 22/tcp

- name: Permit unrestricted access from remainder of cluster
  command: ufw allow from {{ undercloud_cidr }}

- name: Do not enforce forwarding rules with UFW
  lineinfile: dest=/etc/default/ufw regexp="^DEFAULT_FORWARD_POLICY" line="DEFAULT_FORWARD_POLICY=\"ACCEPT\""

- name: Enable UFW (after configuring SSH access)
  command: ufw --force enable
