---
- apt: pkg={{ item }}
  with_items:
    - dnsmasq
    - dnsmasq-utils
    - ucarp

- name: Prevent dnsmasq from add itself to /etc/resolv.conf via resolvconf
  lineinfile: dest=/etc/default/dnsmasq regexp="^DNSMASQ_EXCEPT=" line="DNSMASQ_EXCEPT=lo"

- command: resolvconf -d lo.dnsmasq

- name: ovs ex bridge
  ovs_bridge: name=br-ex state=present
  notify:
    - ifup br-ex

- template: src=etc/init/{{ item }}.conf dest=/etc/init/{{ item }}.conf
  with_items:
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent

- template: src=etc/init/neutron-lbaas-agent.conf dest=/etc/init/neutron-lbaas-agent.conf
  when: neutron.enable_lbaas

- service: name={{ item }} state=started
  with_items:
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent

- service: name=neutron-lbaas-agent state=started
  when: neutron.enable_lbaas

- apt: pkg=python-daemon
- file: dest=/etc/ipchanged/{{ ansible_default_ipv4.interface }}/{{ floating_ip }} state=directory
- template: src=etc/ipchanged/add_floating_ip dest=/etc/ipchanged/{{ ansible_default_ipv4.interface }}/{{ floating_ip }}/add mode=0755
- template: src=usr/local/sbin/ipchanged dest=/usr/local/sbin/ipchanged mode=0755
- template: src=etc/init/ipchanged.conf dest=/etc/init/ipchanged.conf mode=0644
- service: name=ipchanged state=started
