---
- name: add hwraid apt key
  apt_key: id=23B3D3B4 url=http://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key

- name: add hwraid apt repository
  apt_repository: repo='deb http://hwraid.le-vert.net/ubuntu precise main' state=present update_cache=yes

- name: install raid utilities
  apt: pkg={{ item }}
  with_items: common.hwraid.clients
