---
- name: register whether we need to add the hwraid apt-key
  shell: /usr/bin/apt-key list | grep -i hwraid.le-vert.net > /dev/null 2>&1
  ignore_errors: True
  register: has_key

- name: add hwraid apt key
  apt_key: url='http://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key' state=present
  when: not has_key.rc == 0

- name: add hwraid apt repository
  apt_repository: repo="deb http://hwraid.le-vert.net/ubuntu precise main" state=present update_cache=yes

- name: install raid utilities
  apt: pkg={{ item }}
  with_items: common.hwraid.clients
