---
- copy: content={{ network_interfaces }} dest=/etc/network/interfaces force=yes owner=root group=root mode=0644
  when: network_interfaces is defined

- copy: content={{ item.contents }} dest=/etc/network/interfaces.d/{{ item.filename }} force=yes owner=root group=root mode=0644
  when: network_interfaces_d is defined
  with_items: network_interfaces_d

- template: src=etc/sysctl.d/60-netfilter-tuning.conf dest=/etc/sysctl.d/60-netfilter-tuning.conf owner=root group=root mode=0644
  notify:
    - apply-sysctl

- template: src=etc/sysctl.d/60-tcp-tuning.conf dest=/etc/sysctl.d/60-tcp-tuning.conf owner=root group=root mode=0644
  notify:
    - apply-sysctl

- template: src=etc/modprobe.d/conntrack.conf dest=/etc/modprobe.d/conntrack.conf owner=root group=root mode=0644

- lineinfile: dest=/etc/hosts regexp=^127.0.0.1 line="127.0.0.1 {{ ansible_fqdn }} {{ ansible_hostname }} localhost.localdomain localhost"

- lineinfile: dest=/etc/hosts regexp=^{{ item.ip }} line="{{ item.ip }} {{ item.name }}"
  with_items: etc_hosts

- lineinfile: dest=/etc/sysctl.d/10-ipv6-privacy.conf regexp=^net\.ipv6\.conf\.all\.use_tempaddr line="net.ipv6.conf.all.use_tempaddr = 0"
  notify:
    - apply-sysctl

- lineinfile: dest=/etc/sysctl.d/10-ipv6-privacy.conf regexp=^net\.ipv6\.conf\.default\.use_tempaddr line="net.ipv6.conf.default.use_tempaddr = 0"
  notify:
    - apply-sysctl
