---
- template: src=etc/network/interfaces dest=/etc/network/interfaces owner=root group=root mode=0644
  when: network_interfaces is defined

- lineinfile: dest=/etc/sysctl.d/10-ipv6-privacy.conf regexp=^net\.ipv6\.conf\.all\.use_tempaddr line="net.ipv6.conf.all.use_tempaddr = 0"
  notify:
    - apply-sysctl

- lineinfile: dest=/etc/sysctl.d/10-ipv6-privacy.conf regexp=^net\.ipv6\.conf\.default\.use_tempaddr line="net.ipv6.conf.default.use_tempaddr = 0"
  notify:
    - apply-sysctl
